### ISSUE TITLE
Add development branch for the latest development version of RDMO

### ISSUE THREAD

**Issue by m6121** [rdmorganiser/rdmo-docker-compose#13]
For users testing the latest development version such as for RDMO v1.6 it would be very helpful to have a corresponding dev branch for this docker-compose setup that installs the development branch of RDMO including the corresponding dependencies. We would be happy to contribute these adjustments.

Furthermore, the following might be adjusted:
* nginx: docker-master might be added an `apt upgrade -y` as in the postgres specification; Maybe it is also worth to switch to the nginx docker-images
* add a re-build command to the makefile which pulls the latest docker-images used as a basis and re-builds the custom images

**Comment by m6121** [comment]
As proposed above I created a dev branch in my fork that I would be happy to contribute with a PR: https://github.com/m6121/rdmo-docker-compose/tree/dev

This branch includes the installation of the latest RC of rdmo and the following changes:
* The `makefile` contains an explicit `run_pull` in order to pull the latest container for security reasons
* The base container was changed from `debian:10` to `debian:stable` 
* With respect to the [docker recommendations for apt-commands](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) each layer includes an `apt update` and cleares the apt cache, now.

I also introduced additional variables in the dev branch for:
* The base volume directory can be set in the `makefile` using the `VOLDIR`. This allows to easily put the volumes outside of the `rdmo-docker-compose` directory, of course file permissions need to be set correctly.
* `DJANGO_SECRET_KEY` can be set in the `variables.local` and a not very useful default value is set in `variables.env`. This allows to easily set this important value.

**Comment by triole** [comment]
Hi, I made a branch inside the rdmo repo which basically consists of your pull request. The are only a few tiny changes I made.

I added a switch which allows to define an `RDMO_INSTALLATION_URL` in the `variables.env`. This setting makes it possible to switch between installing from pip or installing from github. That's because I'd like to avoid maintaining two different branches in the future. So although this setting should be used with caution, which by the way is why it wasn't added already, it seems to make sense for testing rdmo release candidates.

https://github.com/rdmorganiser/rdmo-docker-compose/tree/m6121-dev

**Comment by m6121** [comment]
Hi @triole,

this looks great. Thanks for the additional changes and thanks for creating the branch. As the variable you inserted allows to easily switch between dev/prod in the local variables file, a dedicated dev branch might not be needed if the changes are also in the master branch.

Best regards,
Max
