### ISSUE TITLE
Some issues with init: unprecise postgres version, failed init of rdmo-app and slow postgres init

### ISSUE THREAD

**Issue by jannefleischer** [rdmorganiser/rdmo-docker-compose#31]
Today I had some issues when initiating rdmo. There where three relevant issues:

1. postgres:latest - this used a local version of postgres:latest from 2020. Obviously User-Error, but maybe the baseconf.toml should contain a specific (minimum) version by default. 15 seem to run fine.
2. #29 provided a fix for a missing rdmo-app: It won't get installed if there is an empty rdmo-app folder: So I had to comment out the creation of that folder in `sh/prepare.sh`: `#mkdir -p ${VOLDIR}/rdmo-app`
3. On first run initdb of postgres takes some time, so rdmo_app is failing to connect to db. I needed to add a healthcheck to postgres service and made rdmo dependendent on that healthcheck. I will provide a pull request for that.

**Comment by triole** [comment]
Hi... sorry that my reply took a momen. I was on holiday and did not find the time to write an answer until now. Here is what I think about your three points:

1. Honestly I am not much of a fan of pinning certain old software versions into config files. This is why I decided to use `postgres:latest`. Of course you are right and this might be considered as a problem if a user has an old image version in his docker cache because docker will use what is already pulled. But it could also be seen as feature because having this implemented as default setting, docker will by default only pull data when it is absolutely necessary. If you do not want that you can always manually clean your cache or add a version number in your `conf.toml`. So to be honest I would prefer to leave it as it is. Having an old version (whatever this version might be) in the default settings poses other problems. Like for example long and painful discussions which version this might be. Or forcing a certain version number on users by default where it would have been better to just use the most up to date piece of software.

2. This is surely something that needs to be investigated further. I need a little time for this but will comment as soon as I have an idea how to solve this. So please consider this as postponed for now.

3. I know that the server start fails when the database is not ready but I intentionally decided against having a check for that. The reason being that this kind of check would involve `pg_isready` which is part of the `postgresql-client` package. I wanted to keep the number of dependencies and necessary sofware packages at a minimum which is why I did not want to install this package which I consider essentially as not being necessary. The app call in the `drun.sh` is in a loop so if the app fails to start, it should just try to start again until it is up and running. There shouldn't be any recognizable problem if the start fails a few times because it will work at some point. So as I see it a pg_isready check would not solve any problem which is why I vote against adding additional software packets to the container.

**Comment by triole** [comment]
I merged your pull request. The newly implemented healthcheck makes sense and is slightly different from what I am describing above. Nonentheless I will make some tests concerning the mkdir command because I am still not sure if removing it will work in any case.

**Comment by jannefleischer** [comment]
Main issues are addressed, so I close this! Thanks.
