### ISSUE TITLE
BASE_URL doesn't apply to all paths

### ISSUE THREAD

**Issue by suchmaske** [rdmorganiser/rdmo-docker-compose#9]
When deploying `rdmo` with a subdomain, it seems that not all paths are being rewritten correctly.

```
rdmo/vol/rdmo-app/config/settings/local.py
--
BASE_URL = '/rdmo'
```
For instance, when visiting the index page, the "Login"/"Anmelden" link in the navbar correctly routes to `/rdmo/account/login`.

However, other routes (for changing the locale) or routes within forms are not being prepended with the BASE_URL. For example, the link to the registration form or the POST-URL for the login form does not re-route correctly.

Although the BASE_URL is configured, the URLs point to:

* `/account/login` instead of `/rdmo/account/login`
* `/account/signup` instead of `/rdmo/account/signup`
* `/i18n/en` instead of `/rdmo/i18n/en`
etc.

![grafik](https://user-images.githubusercontent.com/4989253/67215641-221e7e80-f422-11e9-8380-c8ff759add58.png)

This routing issue makes the app unusable for users when trying to deploy under a server subdirectory path (e.g. `example.com/rdmo`).

My nginx-snippet on the host OS.

```
location / {
  proxy_pass http://localhost:8484/;
}
```

**Comment by triole** [comment]
During testing the setup again I was not able reproduce the problems you mentioned above. Nonetheless I made tiny changes to make the software a little more error resilient. But these changes shouldn't be connected to what you observed.

Maybe I need a little more information about what you were trying to achieve. Because if I just run the whole setup, building the docker containers from the scratch and opening `localhost:8484/rdmo` afterwards I do not have any redirecting problems. 

How do you run your stuff? And what role exactly does the Nginx play? If you use it as a reverse proxy in front of the Apache we need to make sure that the Nginx setup is correct. The problem could be buried somewhere there as well.

**Comment by johlton** [comment]
Sorry to reopen this but this is exactly what happens in my docker-compose installation. The problem might be the proxy, indeed. In my case it's just a simple Apache Docker proxy config: 

````
ProxyPass /rdmo/ http://127.0.0.1:8484/
ProxyPassReverse /rdmo/ http://127.0.0.1:8484/
````

I have the `BASE_PATH` in `variables.env` set to `/rdmo`. What is the current status for the _"NOTE: BASE_URL does not work, will be fixed later"_ message? Might this be the reason for the problem here?

I can see the home view but as the OP says the contained links do not have it. So where to go from here? Any suggestions are highly appreciated. Thanks.
